### ISSUE TITLE
Warning: Invalid prop `className` supplied to `React.Fragment`.

### ISSUE THREAD

**Issue by knoopx** [Craftsy/babel-plugin-encapsulate-jsx#1]

**Comment by chandlerprall** [comment]
Thanks for filing! I've added support to exclude some elements, defaulting to `React.Fragment` and `Fragment`. As this could break someone's setup I've bumped to a new major version with an `rc1` flag for testing.

Please upgrade to `babel-plugin-encapsulate-jsx@3.0.0-rc1` and let me know if it resolves the warning for you.
